[package]
name = "smol-sd-none-client"
version = "0.1.0"
edition = "2021"

[dependencies]
smol-sd-none = { path = "../", features = ["client"] }
lyanne = { path = "../../../", features = ["rt_smol", "client", "no_panics"] }
smol = { version = "^2.0.0" }
rand = "^0.8.0"
