[workspace]
resolver = "2"
members = [
    "derive",
    "examples/bevy-ping-pong",
    "examples/bevy-ping-pong/client",
    "examples/bevy-ping-pong/server",
]

[package]
name = "lyanne"
version = "0.1.0"
edition = "2021"

[features]
default = []
client = ["lyanne-derive/client"]
server = ["lyanne-derive/server"]
troubles_simulator = []

rt-tokio = ["dep:tokio"]
rt-bevy = [
    "dep:bevy_tasks",
    "dep:async-net",
    "dep:async-lock",
    "dep:futures",
    "dep:futures-timer",
]

sd-bincode = [
    "lyanne-derive/sd-bincode",
    "dep:serde",
    "dep:bincode",
    "dep:bincode",
]

bevy-packet-schedules = ["lyanne-derive/bevy-packet-schedules", "dep:bevy_ecs"]

[dependencies]
lyanne-derive = { path = "derive" }
rand = "^0.8.0"
dashmap = "^6.0.0"
x25519-dalek = "^2.0.0"
chacha20poly1305 = "^0.10.0"
colored = "2.0"
async-channel = "^2.0.0"

smol = { version = "^2.0.0", optional = true }
async-std = { version = "^1.0.0", optional = true }

# rt-bevy
tokio = { version = "^1.0.0", optional = true, features = [
    "net",
    "rt-multi-thread",
] }
# rt-bevy
bevy_tasks = { version = "^0.14.0", optional = true }
async-net = { version = "^2.0.0", optional = true }
async-lock = { version = "^3.0.0", optional = true }
futures = { version = "^0.3", optional = true, features = ["alloc"] }
futures-timer = { version = "^3.0.0", optional = true }

bevy_ecs = { version = "^0.14.0", optional = true }

# sd-bincode
serde = { version = "^1.0.0", features = ["derive"], optional = true }
bincode = { version = "^1.0.0", optional = true }
