[workspace]
resolver = "2"
members = [
    "derive",
    "examples/bevy-ping-pong",
    "examples/bevy-ping-pong/client",
    "examples/bevy-ping-pong/server",
]

[package]
name = "lyanne"
version = "0.1.0"
edition = "2021"

[features]
default = []
client = ["lyanne-derive/client"]
server = ["lyanne-derive/server"]

rt_tokio = ["dep:tokio"]
rt_bevy = [
    "dep:bevy_tasks",
    "dep:async-net",
    "dep:async-lock",
    "dep:futures",
    "dep:futures-timer",
]

sd_bincode = [
    "lyanne-derive/sd_bincode",
    "dep:serde",
    "dep:bincode",
    "dep:bincode",
]

bevy_packet_schedules = ["lyanne-derive/bevy_packet_schedules", "dep:bevy_ecs"]
deserialized_message_map = []
troubles_simulator = []
auth_tcp = []
auth_tls = ["dep:tokio-rustls", "dep:futures-rustls", "dep:rustls-pemfile"]

[dependencies]
lyanne-derive = { path = "derive" }
rand = "^0.8.0"
dashmap = "^6.0.0"
x25519-dalek = "^2.0.0"
chacha20poly1305 = "^0.10.0"
colored = "2.0"
async-channel = "^2.0.0"

smol = { version = "^2.0.0", optional = true }
async-std = { version = "^1.0.0", optional = true }

# rt_tokio
tokio = { version = "^1.0.0", optional = true, features = [
    "net",
    "rt-multi-thread",
] }
# rt_bevy
bevy_tasks = { version = "^0.14.0", optional = true }
async-net = { version = "^2.0.0", optional = true }
async-lock = { version = "^3.0.0", optional = true }
futures = { version = "^0.3", optional = true, features = ["alloc"] }
futures-timer = { version = "^3.0.0", optional = true }

bevy_ecs = { version = "^0.14.0", optional = true }

# sd_bincode
serde = { version = "^1.0.0", features = ["derive"], optional = true }
bincode = { version = "^1.0.0", optional = true }

#auth_tls
futures-rustls = { version = "^0.26.0", optional = true }
tokio-rustls = { version = "^0.26.0", optional = true }
rustls-pemfile = { version = "^2.0.0", optional = true }
