[workspace]
resolver = "2"
members = [
    "derive",
    "examples/bevy-ping-pong",
    "examples/bevy-ping-pong/client",
    "examples/bevy-ping-pong/server",
]

[package]
name = "lyanne"
version = "0.1.0"
edition = "2021"

[features]
default = ["bevy", "troubles_simulator", "client", "server"]
bevy = ["dep:bevy", "lyanne-derive/bevy"]
troubles_simulator = []
client = ["lyanne-derive/client"]
server = ["lyanne-derive/server"]

[dependencies]
lyanne-derive = { path = "derive" }
tokio = { version = "^1.0.0", features = ["net", "rt-multi-thread"] }
tokio-util = "^0.7.0"
serde = { version = "^1.0.0", features = ["derive"] }
bincode = "^1.0.0"
bevy = { version = "^0.13.0", optional = true }
crossbeam-channel = { version = "^0.5" }
rand = "^0.8.0"
dashmap = "^6.0.0"
chacha20poly1305 = "^0.10.0"
colored = "2.0"
