[workspace]
resolver = "2"
members = [
    "derive",
    "examples/bevy-ping-pong",
    "examples/bevy-ping-pong/client",
    "examples/bevy-ping-pong/server",
]

[package]
name = "lyanne"
version = "0.1.0"
edition = "2021"

[features]
# TODO: remove bevy, client and server from default features
default = ["bevy", "troubles_simulator", "client", "server"]
bevy = ["dep:bevy_ecs", "lyanne-derive/bevy"]
troubles_simulator = []
client = ["lyanne-derive/client"]
server = ["lyanne-derive/server"]

[dependencies]
lyanne-derive = { path = "derive" }
tokio = { version = "^1.0.0", features = ["net", "rt-multi-thread"] }
tokio-util = "^0.7.0"
serde = { version = "^1.0.0", features = ["derive"] }
bincode = "^1.0.0"
bevy_ecs = { version = "^0.14.0", optional = true }
rand = "^0.8.0"
dashmap = "^6.0.0"
x25519-dalek = "^2.0.0"
chacha20poly1305 = "^0.10.0"
colored = "2.0"
async-channel = "^2.0.0"
