[workspace]
resolver = "2"
members = [ 
    "derive",
    "examples/bevy-ping-pong", 
    "examples/bevy-ping-pong/client", 
    "examples/bevy-ping-pong/server",
]

[package]
name = "lyanne"
version = "0.1.0"
edition = "2021"

[features]
default = [ "use_bevy", "troubles_simulator", "client", "server" ]
use_bevy = [ "bevy", "lyanne-derive/use_bevy" ]
troubles_simulator = [ ]
client = [ "lyanne-derive/client" ]
server = [ "lyanne-derive/server" ]

[dependencies]
lyanne-derive = { path = "derive" }
tokio = { version = "^1.0.0", features = [ "full" ] }
serde = { version = "^1.0.0", features = [ "derive" ] }
bincode = "^1.0.0"
bevy = { version = "^0.13.0", optional = true }
crossbeam-channel = { version = "^0.5" }
rand = "^0.8.0"
colored = "2.0"
dashmap = "^5.0.0"