[package]
name = "async-std-simple-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std-simple = { path = "../", features = ["server"] }
lyanne = { path = "../../../", features = ["rt_async_std", "server"] }
async-std = { version = "^1.12.0" }
rand = "^0.8.0"
