[package]
name = "lyanne-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "^2.0.0"
quote = "^1.0.0"

[features]
client = []
server = []
bevy-packet-schedules = []

[lib]
proc-macro = true
