[package]
name = "tokio-simple-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-simple = { path = "../", features = ["server"] }
lyanne = { path = "../../../", features = ["rt_tokio", "server"] }
tokio = { version = "^1.0.0", features = ["full"] }
rand = "^0.8.0"
