[workspace]

[package]
name = "async-std-tcp"
version = "0.1.0"
edition = "2021"

[features]
client = ["lyanne/client"]
server = ["lyanne/server"]

[dependencies]
lyanne = { path = "../../", features = ["sd_bincode"] }
serde = { version = "^1.0.0", features = ["derive"] }
