[package]
name = "damas-client"
version = "0.1.0"
edition = "2021"

[dependencies]
damas = { path = "../" }
lyanne = { path = "../../../", features = [ "client" ] }
tokio = { version = "^1.0.0", features = [ "full" ] }
rand = "^0.8.0"