[package]
name = "smol-simple-server"
version = "0.1.0"
edition = "2021"

[dependencies]
smol-simple = { path = "../", features = ["server"] }
lyanne = { path = "../../../", features = ["rt_smol", "server"] }
smol = { version = "^2.0.0" }
rand = "^0.8.0"
