[package]
name = "bevy-ping-pong-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy-ping-pong = { path = "../" }
bevy = "^0.13.0"
lyanne = { path = "../../../", features = [
    "bevy",
    "troubles_simulator",
    "client",
] }
tokio = { version = "^1.0.0", features = ["full"] }
rand = "^0.8.0"
