[workspace]

[package]
name = "smol-simple-client"
version = "0.1.0"
edition = "2021"

[dependencies]
smol-simple = { path = "../", features = ["client"] }
lyanne = { path = "../../../", features = ["rt_smol", "client"] }
smol = { version = "^2.0.0" }
rand = "^0.8.0"
