name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run tests
      run: cargo test --verbose --features "client,server,rt_smol,sd_bincode"

    - name: "Check example: async-executor-simple"
      run: |
        cargo check --manifest-path examples/async-executor-simple/client/Cargo.toml
        cargo check --manifest-path examples/async-executor-simple/server/Cargo.toml
    - name: "Check example: async-std-simple"
      run: |
        cargo check --manifest-path examples/async-std-simple/client/Cargo.toml
        cargo check --manifest-path examples/async-std-simple/server/Cargo.toml
    - name: "Check example: async-std-tcp"
      run: |
        cargo check --manifest-path examples/async-std-tcp/client/Cargo.toml
        cargo check --manifest-path examples/async-std-tcp/server/Cargo.toml
    - name: "Check example: async-std-tls"
      run: |
        cargo check --manifest-path examples/async-std-tls/client/Cargo.toml
        cargo check --manifest-path examples/async-std-tls/server/Cargo.toml
    - name: "Check example: bevy-pong"
      run: |
        cargo check --manifest-path examples/bevy-pong/client/Cargo.toml
        cargo check --manifest-path examples/bevy-pong/server/Cargo.toml
    - name: "Check example: bevy-simple"
      run: |
        cargo check --manifest-path examples/bevy-simple/client/Cargo.toml
        cargo check --manifest-path examples/bevy-simple/server/Cargo.toml
    - name: "Check example: smol-sd-none"
      run: |
        cargo check --manifest-path examples/smol-sd-none/client/Cargo.toml
        cargo check --manifest-path examples/smol-sd-none/server/Cargo.toml
    - name: "Check example: smol-simple"
      run: |
        cargo check --manifest-path examples/smol-simple/client/Cargo.toml
        cargo check --manifest-path examples/smol-simple/server/Cargo.toml
    - name: "Check example: tokio-chat"
      run: |
        cargo check --manifest-path examples/tokio-chat/client/Cargo.toml
        cargo check --manifest-path examples/tokio-chat/server/Cargo.toml
    - name: "Check example: tokio-simple"
      run: |
        cargo check --manifest-path examples/tokio-simple/client/Cargo.toml
        cargo check --manifest-path examples/tokio-simple/server/Cargo.toml
    
