name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run tests
      run: cargo test --verbose --features "client,server,rt_smol,sd_bincode"

    - name: Check all examples
      run: |
        for example in examples/*; do
          if [ -f "$example/Cargo.toml" ]; then
            echo "Checking $example-client..."
            cargo check --manifest-path $example/client/Cargo.toml
            echo "Checking $example-server..."
            cargo check --manifest-path $example/server/Cargo.toml
          fi
        done
