name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run tests
      run: cargo test --verbose --features "client,server,rt_smol,sd_bincode"

    - name: Check all examples
      run: |
        for example in examples/*; do
          if [ -f "$example/Cargo.toml" ]; then
            echo "Checking $example-client..."
            cargo check --manifest-path $example/client/Cargo.toml
            echo "Checking $example-server..."
            cargo check --manifest-path $example/server/Cargo.toml
          fi
        done
